##bank-branch01
server:
  port: 8001

spring:
  application:
    name: service-payment
  datasource:
    username: bank_branch01
    password: scott
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  task:
    scheduling:
      corn: 0/1 * * * * *
      pool:
        size: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true