##bank-branch01
server:
  port: 7000

spring:
  application:
    name: service-schedule
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/schedule_service?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      corn: 0 0/1 * * * *
      pool:
        size: 1
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batch-size: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    consumer:
      enable-auto-commit: false
      group-id: payment-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: payment
    listener:
      missing-topics-fatal: false
      ack-mode: manual

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

fetch-manager:
  fetch-size: 1
  callback-size: 1
  use-batch: true
  batch-size: 2
