##bank-branch01
server:
  port: 7000

spring:
  application:
    name: service-payment
  datasource:
    username: bank_branch01
    password: scott
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  task:
    scheduling:
      corn: 0/1 * * * * *
      pool:
        size: 1
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batch-size: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    consumer:
      enable-auto-commit: false
      group-id: payment-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: payment
    listener:
      missing-topics-fatal: false
      ack-mode: manual

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true