##notification service
server:
  port: 8200

spring:
  application:
    name: service-notification
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pay_router_service?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batch-size: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    consumer:
      enable-auto-commit: false
      group-id: payment-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: payment
    listener:
      missing-topics-fatal: false
      ack-mode: manual


mybatis:
  mapper-locations: classpath:mapper/*.xml

kafka-listener-handler:
  worker-threads: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false #No need to fetch other instances
    register-with-eureka: true

bank-entity:
  current-bank: bank-01

kafka-listened-topics:
  notification: bank-notification